#!/bin/bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
dbus-launch /usr/lib/xdg-desktop-portal-hyprland &
sleep 2
dbus-launch /usr/lib/xdg-desktop-portal &
